name: CI

on:
    push:
    pull_request:

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_test:
        name: Rust project - latest
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain:
                    - stable
                    - nightly
                    - beta
        steps:
            - uses: actions/checkout@v4
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - run: cargo build --verbose
            - run: cargo clippy -- -D warnings
            - run: cargo test --verbose
            - run: cargo +nightly fmt --check
